spring.application.name=api-gateway
server.port=8888

spring.config.import=configserver:http://localhost:9999/configserver

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true